const siteData = {
  nav: [
    { label: "Home", href: "index.html", page: "home" },
    { label: "Events", href: "events.html", page: "events" },
    { label: "Guests", href: "guests.html", page: "guests" },
    { label: "Contact Us", href: "index.html#connect", page: "contact" },
    { label: "About", href: "index.html#about", page: "about" },
  ],
  features: [
    {
      title: "परम्परा",
      emoji: "🌿",
      text: "Celebrating the roots and cultural heritage of Haryana.",
    },
    {
      title: "रचनात्मकता",
      emoji: "🎭",
      text: "A platform for art, music, dance, and bold expression.",
    },
    {
      title: "समुदाय",
      emoji: "🤝",
      text: "Bringing people together through shared experiences.",
    },
  ],
  guestsPreview: [
    { name: "Sh. Manohar Lal Khattar", role: "Former CM, Haryana",image: "assets/Sh. Manohar Lal Khattar (Former CM, Haryana) .png" },
    { name: "Sh. Nayab Singh Saini", role: "CM, Haryana",image: "assets/Sh. Nayab Singh Saini (CM, Haryana).jpg" },
    { name: "Smt. Savitri Jindal", role: "Prominent Industrialist/Social Leader",image: "assets/Smt. Savitri Jindal (Prominent Industrialist:Social Leader) .png" },
    { name: "Sh. Anurag Thakur", role: "Prominent Political Leader",image: "assets/Sh. Anurag Thakur (Prominent Political Leader) .png" },
    { name: "Sh. Bhupender Yadav", role: "Union Minister",image: "assets/Sh. Bhupender Yadav (Union Minister) .jpg" },
    { name: "Sh. Ram Madhav", role: "Prominent Author Leader",image: "assets/Sh. Ram Madhav (Prominent Author:Leader) .jpg" },
  ],
  events: [
    { title: "Escape Room", date: "16 February 2026", category: "Tech Challenge", poster: "assets/event_poster.png" },
    { title: "Kavi Sammelan", date: "17 February 2026", category: "Literature", poster: "assets/event_poster.png" },
    { title: "Rang-e-Haryana", date: "18 February 2026", category: "Cultural", poster: "assets/event_poster.png" },
    { title: "Cinema Chaupal", date: "18 February 2026", category: "Cinema", poster: "assets/event_poster.png" },
    { title: "Media Adda", date: "19 February 2026", category: "Media", poster: "assets/event_poster.png" },
    { title: "Creative Workshop", date: "19 February 2026", category: "Workshop", poster: "assets/event_poster.png" },
    { title: "Folk Performance Night", date: "20 February 2026", category: "Cultural", poster: "assets/event_poster.png" },
    { title: "Idea Sprint", date: "20 February 2026", category: "Innovation", poster: "assets/event_poster.png" },
    { title: "Open Mic Mehfil", date: "21 February 2026", category: "Literature", poster: "assets/event_poster.png" },
    { title: "Campus Dialogues", date: "21 February 2026", category: "Public Talk", poster: "assets/event_poster.png" },
    { title: "Storytelling Circle", date: "22 February 2026", category: "Literature", poster: "assets/event_poster.png" },
    { title: "Startup Spotlight", date: "22 February 2026", category: "Innovation", poster: "assets/event_poster.png" },
  ],
  guestCategories: [
    {
      title: "Chief Guests & Key Dignitaries",
      people: [
        { name: "Sh. Manohar Lal Khattar", role: "Former CM, Haryana" },
        { name: "Sh. Nayab Singh Saini", role: "CM, Haryana" },
        { name: "Smt. Savitri Jindal", role: "Prominent Industrialist/Social Leader" },
        { name: "Sh. Anurag Thakur", role: "Prominent Political Leader" },
        { name: "Sh. Bhupender Yadav", role: "Union Minister" },
        { name: "Sh. Ram Madhav", role: "Prominent Author/Leader" },
      ],
    },
    {
      title: "Literature, Academic & Spiritual Guests",
      people: [
        { name: "Dr. Kapil Sharma", role: "Author & Academician" },
        { name: "Prof. Mahesh Dahiya", role: "Research Mentor" },
        { name: "Dr. Sunita Malik", role: "Poet & Speaker" },
        { name: "Swami Vishal Giri", role: "Spiritual Guide" },
        { name: "Dr. Ritu Kaushik", role: "Educationist" },
        { name: "Sh. Raghav Kaul", role: "Public Thinker" },
        { name: "Smt. Nidhi Awasthi", role: "Writer" },
        { name: "Dr. S. Choudhary", role: "Literary Critic" },
        { name: "Prof. Ramesh Dua", role: "Academic Leader" },
        { name: "Sh. Vinayak Sharma", role: "Motivational Speaker" },
      ],
    },
    {
      title: "Cinema & Arts Personalities",
      people: [
        { name: "Sh. Aditya Rana", role: "Film Director" },
        { name: "Smt. Pooja Sethi", role: "Actor" },
        { name: "Sh. Harsh Bedi", role: "Cinematographer" },
        { name: "Smt. Arohi Tandon", role: "Theatre Artist" },
        { name: "Sh. Darshan Vyas", role: "Music Composer" },
        { name: "Smt. Meenal Ahlawat", role: "Visual Artist" },
        { name: "Sh. Parth Gulati", role: "Creative Producer" },
        { name: "Sh. Naman Kapoor", role: "Art Curator" },
      ],
    },
    {
      title: "Media & Journalism Guests",
      people: [
        { name: "Sh. Vikram Sood", role: "Senior Journalist" },
        { name: "Smt. Isha Jain", role: "News Editor" },
        { name: "Sh. Sameer Rathi", role: "Anchor" },
        { name: "Smt. Kritika Verma", role: "Digital Editor" },
        { name: "Sh. Dev Malhotra", role: "Columnist" },
        { name: "Smt. Reena Batra", role: "Investigative Journalist" },
        { name: "Sh. Arpit Tuli", role: "Media Consultant" },
        { name: "Smt. Niharika Das", role: "Feature Writer" },
        { name: "Sh. Ravi Panwar", role: "Podcast Host" },
        { name: "Smt. Priti Sengar", role: "Story Producer" },
      ],
    },
    {
      title: "Workshop Mentors & Creative Authors",
      people: [
        { name: "Sh. Tarun Ahuja", role: "Workshop Mentor" },
        { name: "Smt. Rashi Gupta", role: "Creative Writer" },
        { name: "Sh. Abhinav Pundir", role: "Leadership Coach" },
        { name: "Smt. Ankita Bansal", role: "Design Mentor" },
        { name: "Sh. Deepak Hooda", role: "Author" },
        { name: "Smt. Prerna Sharma", role: "Storytelling Coach" },
        { name: "Sh. Lokesh Yadav", role: "Workshop Facilitator" },
        { name: "Smt. Shalini Garg", role: "Content Mentor" },
        { name: "Sh. Nishant Walia", role: "Creative Strategist" },
      ],
    },
    {
      title: "Cultural Performers & Artists",
      people: [
        { name: "Haryanvi Folk Ensemble", role: "Traditional Performance Team" },
        { name: "Swar Dhara Group", role: "Music Collective" },
        { name: "Naad Nritya Mandli", role: "Dance Group" },
        { name: "Ragini Sabha", role: "Folk Singers" },
        { name: "Kala Chaupal Artists", role: "Stage Artists" },
        { name: "Raas Rang Manch", role: "Theatre Group" },
        { name: "Pind Beats Crew", role: "Percussion Artists" },
        { name: "Surya Kala Parishad", role: "Folk Performers" },
        { name: "Lok Manch Collective", role: "Cultural Artists" },
      ],
    },
    {
      title: "Coordinating Bodies",
      people: [
        { name: "Team iConnect", role: "Event Coordination Team" },
        { name: "PDUIIC, GJUS&T", role: "Organizing Body" },
      ],
    },
  ],
  contact: {
    address: [
      "iConnect Office, PDUIIC Building,",
      "GJUS&T, Hisar, Haryana - 125001",
    ],
    accommodation: ["+91 9012345678 (Yuvansh)", "+91 9012345678 (Naina)"],
    eventQueries: ["+91 9012345678 (Vansh)", "+91 9012345678 (Naina)"],
    mail: "iconnectgjust@gmail.com",
    socials: ["Instagram", "X", "WhatsApp", "LinkedIn", "Facebook"],
  },
};
